In [0]:
from joblib import load
import numpy as np
import pandas as pd

In [3]:
datapath = 'https://raw.githubusercontent.com/Build-Spotify-flow/Data-science/master/Data/Dataset.csv'
df = pd.read_csv(datapath)
df.head()

artist_name                track_id  ... valence  popularity
0          YG  2RM4jf1Xa9zPgMGRDiht8O  ...   0.118          15
1          YG  1tHDG53xJNGsItRA3vfVgs  ...   0.371           0
2       R3HAB  6Wosx2euFPMT14UXiWudMy  ...   0.382          56
3  Chris Cooq  3J2Jpw61sO7l6Hc7qdYV91  ...   0.641           0
4  Chris Cooq  2jbYvQCyPgX3CdmAzeVeuS  ...   0.928           0

[5 rows x 17 columns]

In [4]:
non_numeric = ['artist_name', 'track_id', 'track_name']
num = df.drop(non_numeric, axis=1)
num.head()

acousticness  danceability  duration_ms  ...  time_signature  valence  popularity
0      0.005820         0.743       238373  ...               4    0.118          15
1      0.024400         0.846       214800  ...               4    0.371           0
2      0.025000         0.603       138913  ...               4    0.382          56
3      0.029400         0.800       125381  ...               4    0.641           0
4      0.000035         0.783       124016  ...               4    0.928           0

[5 rows x 14 columns]

### Using the pickled models!

In [0]:
model = load('/content/NNmodel.joblib')

In [0]:
scaler = load('/content/scaler.joblib')

In [0]:
scaled = scaler.transform(num)

In [0]:
def get_index(song_id):
  '''
  Returns the index number of the song to be used in KDTree model
  
  input must have [] around it!

  Single Example: get_index(['3J2Jpw61sO7l6Hc7qdYV91'])
  
  Multiple Ex: get_index(['3J2Jpw61sO7l6Hc7qdYV91', '6Wosx2euFPMT14UXiWudMy',
                          '2jbYvQCyPgX3CdmAzeVeuS', '7BQaRTHk44DkMhIVNcXy2D'])
  '''
  song_index = []
  for i in song_id:
    song_index.append(df[df['track_id'] == i].index[0])
  return song_index

In [0]:
song_id = ['2RM4jf1Xa9zPgMGRDiht8O']

In [69]:
song_index = get_index(song_id)
song_index

[0]

In [0]:
def recommendations(song_index, k=11):
  '''
  song_index = Index of song(or songs) as seed for recommendations
  
  k = Number of recommendations, default 11 (leaving us with 10 recommendations)
      because first song is input!

  returns distance and indices of each song
  '''
  songs = model.query(scaled[song_index], k=k)
  distance = songs[0]
  indices = songs[1]
  return distance, indices

In [0]:
dist, ind = recommendations(song_index)

In [72]:
# Distance (similarity) from original son
dist

array([[0.        , 1.51707785, 1.53074399, 1.61287789, 1.67284757,
        1.71847884, 1.73613316, 1.76147125, 1.77136484, 1.77275347,
        1.8076944 ]])

In [73]:
# Indices of recommended song
ind

array([[     0,  53717,  51244,  24890,  43424,  92336,  39349, 116877,
         19909,  24230,  57691]])

In [74]:
# Full stats on recommended songs ([1:] to exclude first entry which is always
# the song we are recemmonding from)
df.iloc[ind[0][1:]]

artist_name                track_id  ... valence  popularity
53717     Swank Davis  2ogGsvbGjJz71Ppc9mTExA  ...   0.292           0
51244     Paul Ma$$on  56GWUZPELOP1nK4hQwfVVV  ...   0.127          17
24890           Gyyps  02s1Voowwhr0qTSOrMVEXk  ...   0.310          19
43424       Don Macki  1rG9U7m2wqM0AVmZeIsdtz  ...   0.217           0
92336          T-Pain  3UDOPqusSZZ7NqyWyMMk50  ...   0.103          28
39349             HBK  7oDuAatXvqWD8DAa87KRJ2  ...   0.222          16
116877         Ca$his  0MiAP4EQGIuikH23RTyP53  ...   0.219           7
19909           Caash  2lD4dQpcac8H2Rq5nttJJh  ...   0.142           0
24230   Secret Circle  2MwIkkJujEmXa7o9Nc6HeI  ...   0.310           0
57691           Rah-C  06oDi0OztS33sxfYtxJPO2  ...   0.258          14

[10 rows x 17 columns]

In [75]:
# Just the track_ids as array
df['track_id'].iloc[ind[0][1:]].values

array(['2ogGsvbGjJz71Ppc9mTExA', '56GWUZPELOP1nK4hQwfVVV',
       '02s1Voowwhr0qTSOrMVEXk', '1rG9U7m2wqM0AVmZeIsdtz',
       '3UDOPqusSZZ7NqyWyMMk50', '7oDuAatXvqWD8DAa87KRJ2',
       '0MiAP4EQGIuikH23RTyP53', '2lD4dQpcac8H2Rq5nttJJh',
       '2MwIkkJujEmXa7o9Nc6HeI', '06oDi0OztS33sxfYtxJPO2'], dtype=object)

In [76]:
# As a list
df['track_id'].iloc[ind[0][1:]].to_list()

['2ogGsvbGjJz71Ppc9mTExA',
 '56GWUZPELOP1nK4hQwfVVV',
 '02s1Voowwhr0qTSOrMVEXk',
 '1rG9U7m2wqM0AVmZeIsdtz',
 '3UDOPqusSZZ7NqyWyMMk50',
 '7oDuAatXvqWD8DAa87KRJ2',
 '0MiAP4EQGIuikH23RTyP53',
 '2lD4dQpcac8H2Rq5nttJJh',
 '2MwIkkJujEmXa7o9Nc6HeI',
 '06oDi0OztS33sxfYtxJPO2']

In [77]:
# As a dict/json
df['track_id'].iloc[ind[0][1:]].to_dict()

{19909: '2lD4dQpcac8H2Rq5nttJJh',
 24230: '2MwIkkJujEmXa7o9Nc6HeI',
 24890: '02s1Voowwhr0qTSOrMVEXk',
 39349: '7oDuAatXvqWD8DAa87KRJ2',
 43424: '1rG9U7m2wqM0AVmZeIsdtz',
 51244: '56GWUZPELOP1nK4hQwfVVV',
 53717: '2ogGsvbGjJz71Ppc9mTExA',
 57691: '06oDi0OztS33sxfYtxJPO2',
 92336: '3UDOPqusSZZ7NqyWyMMk50',
 116877: '0MiAP4EQGIuikH23RTyP53'}

### Using 2 Songs

In [78]:
song_id = ['2RM4jf1Xa9zPgMGRDiht8O', '1tHDG53xJNGsItRA3vfVgs']
song_index = get_index(song_id)
song_index

[0, 1]

In [0]:
dist, ind = recommendations(song_index)

In [80]:
# Distance (similarity) from original songs
dist

array([[0.        , 1.51707785, 1.53074399, 1.61287789, 1.67284757,
        1.71847884, 1.73613316, 1.76147125, 1.77136484, 1.77275347,
        1.8076944 ],
       [0.        , 1.19710936, 1.2072914 , 1.23143485, 1.2427973 ,
        1.27617768, 1.29284688, 1.39535769, 1.40511457, 1.41506049,
        1.43229805]])

In [81]:
# Indices of recommended songs
ind

array([[     0,  53717,  51244,  24890,  43424,  92336,  39349, 116877,
         19909,  24230,  57691],
       [     1,  82704,  79610,  81094, 100569,  84494,  67682,  87994,
         21132,  54058,  50984]])

In [82]:
# Full stats on recommended songs ([1:] to exclude first entry which is always
# the song we are recemmonding from) for the first input
df.iloc[ind[0][1:]]

artist_name                track_id  ... valence  popularity
53717     Swank Davis  2ogGsvbGjJz71Ppc9mTExA  ...   0.292           0
51244     Paul Ma$$on  56GWUZPELOP1nK4hQwfVVV  ...   0.127          17
24890           Gyyps  02s1Voowwhr0qTSOrMVEXk  ...   0.310          19
43424       Don Macki  1rG9U7m2wqM0AVmZeIsdtz  ...   0.217           0
92336          T-Pain  3UDOPqusSZZ7NqyWyMMk50  ...   0.103          28
39349             HBK  7oDuAatXvqWD8DAa87KRJ2  ...   0.222          16
116877         Ca$his  0MiAP4EQGIuikH23RTyP53  ...   0.219           7
19909           Caash  2lD4dQpcac8H2Rq5nttJJh  ...   0.142           0
24230   Secret Circle  2MwIkkJujEmXa7o9Nc6HeI  ...   0.310           0
57691           Rah-C  06oDi0OztS33sxfYtxJPO2  ...   0.258          14

[10 rows x 17 columns]

In [83]:
# Full stats on recommended songs ([1:] to exclude first entry which is always
# the song we are recemmonding from) for the second input
df.iloc[ind[1][1:]]

artist_name                track_id  ... valence  popularity
82704   Yung Finnatic$  76wqmxKVKXradVxmfGpZfX  ...   0.292           0
79610      Kenny Muney  0x1MJ34QQHGK9nTmOdSe33  ...   0.313          10
81094     Mark Battles  0D8Qknpc7ZtnOU4pEwXGos  ...   0.422           3
100569          Mukesh  3eUyRzsgH4Vjraw3oVqVDg  ...   0.418           0
84494     Kacee Playaa  51jT8cWCrANwOvDkzqKpF4  ...   0.266           0
67682           'Lgado  7vBFNgj6XAYYcp6pKuvjp2  ...   0.330           7
87994              G2g  4uO9h2EWJqr1ViWEON957k  ...   0.281           3
21132      Chevy Woods  1Dfwu69pIy52gVUzbJ6Bwk  ...   0.400          14
54058       M.I. Abaga  1SE0FG6lc3MMZoHj65DTVq  ...   0.471           0
50984         Beatking  7A5WzjLKRSglnolIcKDJHm  ...   0.523          15

[10 rows x 17 columns]